#!/bin/sh

set -e

echo "+++ Building and pushing application image"

RUBY_VERSION=$(cat .ruby-version)

docker buildx build . \
  --build-arg RUBY_VERSION=$RUBY_VERSION \
  --platform linux/amd64 \
  -t europe-north1-docker.pkg.dev/kubernetes-367912/mynewsdesk/devops-talos-manager:sha-$BUILDKITE_COMMIT \
  --cache-from type=registry,ref=europe-north1-docker.pkg.dev/kubernetes-367912/mynewsdesk/devops-talos-manager \
  --cache-to type=registry,ref=europe-north1-docker.pkg.dev/kubernetes-367912/mynewsdesk/devops-talos-manager \
  --progress plain \
  --push
