default: &default
  <% if ENV["DB_ADAPTER"] == "sqlite" %>
  adapter: sqlite3
  timeout: 5000
  <% else %>
  adapter: postgresql
  encoding: unicode
  <% end %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  <% if ENV["DB_ADAPTER"] == "sqlite" %>
  database: storage/development.sqlite3
  <% else %>
  database: talos_manager_development
  <% end %>

test:
  <<: *default
  <% if ENV["DB_ADAPTER"] == "sqlite" %>
  database: storage/test.sqlite3
  <% else %>
  database: talos_manager_test
  <% end %>

production:
  <<: *default
  <% if ENV["DB_ADAPTER"] == "sqlite" %>
  database: storage/production.sqlite3
  <% else %>
  # NOTE: You should be relying on DATABASE_URL when using Postgres in production
  database: talos_manager_production
  <% end %>