on: push

jobs:
  specs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: .github/specs
        shell: script --return --quiet --command "bash {0}" # enable TTY for color output

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: depot/build-push-action@v1
        with:
          project: 8cd70jhtnd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            reclaimthestack/talos-manager:latest
            reclaimthestack/talos-manager:sha-${{ github.sha }}
